-- DB2: modelo relacional cadastro de socios (fase 2 - substitui ADABAS)
-- Grupo periodico PERIODICO-PAGAMENTO -> tabela filha 1:N (sem limite artificial).

CREATE TABLE CLIENTE (
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)   NOT NULL,
    NOME_SOCIO_PRINCIPAL    VARCHAR(40)     NOT NULL,
    DATA_CADASTRO           DATE            NOT NULL,
    CATG_SOCIO              SMALLINT        NOT NULL,
    INDI_DIVIDA             SMALLINT        NOT NULL DEFAULT 0,
    DATA_BAIXA              DATE,
    HORA_BAIXA              VARCHAR(12),
    OBSV_CLIENTE            VARCHAR(500)    NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY (NUMB_SOCIO_PRINCIPAL)
);

CREATE TABLE CLIENTE_PAGAMENTO (
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)   NOT NULL,
    SEQUENCIA               SMALLINT        NOT NULL,
    DATA_VENCIMENTO         DATE            NOT NULL,
    VALR_MENSALIDADE        DECIMAL(8, 2)   NOT NULL,
    PAGAMENTO_OK            CHAR(1)         NOT NULL,
    CONSTRAINT PK_CLIENTE_PAGAMENTO
        PRIMARY KEY (NUMB_SOCIO_PRINCIPAL, SEQUENCIA),
    CONSTRAINT FK_CLIENTE_PAGAMENTO_CLIENTE
        FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES CLIENTE (NUMB_SOCIO_PRINCIPAL)
        ON DELETE CASCADE
);

CREATE INDEX IX_CLIENTE_PAG_VENC
    ON CLIENTE_PAGAMENTO (DATA_VENCIMENTO);
