-- DB2 Script for SOCIOS Tables Migration
-- Source: ADABAS-SOCIOS (DBID 0, FNR 24)
-- Created: 2026-05-26

-- Create main SOCIOS table
CREATE TABLE SOCIOS (
    NUMB_SOCIO_PRINCIPAL    NUMERIC(9,0)   NOT NULL PRIMARY KEY,
    NOME_SOCIO_PRINCIPAL    CHAR(40)       NOT NULL,
    DATA_CADASTRO           DATE           NOT NULL,
    CATG_SOCIO              SMALLINT       NOT NULL,
    INDI_DIVIDA             CHAR(1)        NOT NULL DEFAULT '0',
    DATA_BAIXA              DATE           NULL,
    HORA_BAIXA              TIME(0)        NULL,
    OBSV_SOCIO              VARCHAR(500)   NULL
)
IN USERSPACE1
ORGANIZE BY KEY SEQUENCE;

-- Create periodic table for payments
CREATE TABLE SOCIOS_PAGAMENTO (
    NUMB_SOCIO_PRINCIPAL    NUMERIC(9,0)   NOT NULL,
    SEQ_PAGAMENTO           SMALLINT       NOT NULL,
    DATA_VENCIMENTO         DATE           NOT NULL,
    VALR_MENSALIDADE        DECIMAL(6,2)   NOT NULL,
    PAGAMENTO_OK            CHAR(1)        NOT NULL DEFAULT '0',
    PRIMARY KEY (NUMB_SOCIO_PRINCIPAL, SEQ_PAGAMENTO),
    FOREIGN KEY (NUMB_SOCIO_PRINCIPAL) REFERENCES SOCIOS(NUMB_SOCIO_PRINCIPAL)
        ON DELETE CASCADE
)
IN USERSPACE1;

-- Create SUPER descriptor index (CATG-SOCIO + INDI-DIVIDA)
CREATE INDEX IX_SOCIOS_SUPER1
    ON SOCIOS(CATG_SOCIO, INDI_DIVIDA);

-- Create index for payment queries
CREATE INDEX IX_SOCIOS_PAGAMENTO_VENC
    ON SOCIOS_PAGAMENTO(NUMB_SOCIO_PRINCIPAL, DATA_VENCIMENTO);

COMMIT;
