-- DB2: member (SOCIO) and recurring payment history (SOCIO_PAGAMENTO).
-- Phase 2: periodic group from legacy becomes a child table (unlimited rows).

CREATE TABLE SOCIO (
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)   NOT NULL,
    NOME_SOCIO_PRINCIPAL    VARCHAR(40)     NOT NULL,
    DATA_CADASTRO           DATE            NOT NULL,
    CATG_SOCIO              SMALLINT        NOT NULL,
    INDI_DIVIDA             SMALLINT        NOT NULL,
    DATA_BAIXA              DATE,
    HORA_BAIXA              VARCHAR(12),
    OBSV_SOCIO              VARCHAR(500)    NOT NULL,
    CONSTRAINT PK_SOCIO PRIMARY KEY (NUMB_SOCIO_PRINCIPAL)
);

CREATE TABLE SOCIO_PAGAMENTO (
    PAGAMENTO_ID            BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1),
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)   NOT NULL,
    SEQ_LINHA               INTEGER         NOT NULL,
    DATA_VENCIMENTO         DATE            NOT NULL,
    VALR_MENSALIDADE        DECIMAL(8, 2) NOT NULL,
    PAGAMENTO_OK            CHAR(1)         NOT NULL,
    CONSTRAINT PK_SOCIO_PAGAMENTO PRIMARY KEY (PAGAMENTO_ID),
    CONSTRAINT FK_SOCIO_PAGAMENTO_SOCIO FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES SOCIO (NUMB_SOCIO_PRINCIPAL) ON DELETE CASCADE
);

CREATE UNIQUE INDEX UX_SOCIO_PAGAMENTO_SEQ
    ON SOCIO_PAGAMENTO (NUMB_SOCIO_PRINCIPAL, SEQ_LINHA);

CREATE INDEX IX_SOCIO_PAGAMENTO_SOCIO
    ON SOCIO_PAGAMENTO (NUMB_SOCIO_PRINCIPAL);
