-- DDL DB2 - migracao ADABAS-SOCIOS (DBATDP-18)
-- Entidade principal e tabela filha 1:N para PERIODICO-PAGAMENTO

CREATE TABLE SOCIO (
    NUMB_SOCIO_PRINCIPAL  DECIMAL(9, 0) NOT NULL,
    NOME_SOCIO_PRINCIPAL  VARCHAR(40)   NOT NULL,
    DATA_CADASTRO         DATE          NOT NULL,
    CATG_SOCIO            SMALLINT      NOT NULL,
    INDI_DIVIDA           CHAR(1)       NOT NULL,
    DATA_BAIXA            DATE,
    HORA_BAIXA            CHAR(5),
    OBSV_SOCIO            VARCHAR(500),
    CONSTRAINT PK_SOCIO PRIMARY KEY (NUMB_SOCIO_PRINCIPAL)
);

-- SUPER1 ADABAS (BA+BB): CATG-SOCIO + INDI-DIVIDA
CREATE INDEX IDX_SOCIO_SUPER1 ON SOCIO (
    CATG_SOCIO,
    INDI_DIVIDA
);

CREATE TABLE SOCIO_PERIODICO_PAGAMENTO (
    NUMB_SOCIO_PRINCIPAL  DECIMAL(9, 0) NOT NULL,
    SEQ_PERIODICO         INTEGER       NOT NULL,
    DATA_VENCIMENTO       DATE          NOT NULL,
    VALR_MENSALIDADE      DECIMAL(6, 2) NOT NULL,
    PAGAMENTO_OK          CHAR(1)       NOT NULL,
    CONSTRAINT PK_SOCIO_PERIODICO_PAGAMENTO
        PRIMARY KEY (NUMB_SOCIO_PRINCIPAL, SEQ_PERIODICO),
    CONSTRAINT FK_SOCIO_PERIODICO_SOCIO
        FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES SOCIO (NUMB_SOCIO_PRINCIPAL)
);
