-- DBATDP-18: Tabela filha 1N - grupo periódico PERIODICO-PAGAMENTO

CREATE TABLE SOCIO_PAGAMENTO (
    NUMB_SOCIO_PRINCIPAL  DECIMAL(9, 0)  NOT NULL,
    NUM_PAGAMENTO         SMALLINT       NOT NULL,
    DATA_VENCIMENTO       DATE           NOT NULL,
    VALR_MENSALIDADE      DECIMAL(6, 2)  NOT NULL,
    PAGAMENTO_OK          CHAR(1)        NOT NULL
        CONSTRAINT CHK_SOCIO_PAG_OK
            CHECK (PAGAMENTO_OK IN ('Y', 'N')),
    CONSTRAINT PK_SOCIO_PAGAMENTO
        PRIMARY KEY (NUMB_SOCIO_PRINCIPAL, NUM_PAGAMENTO),
    CONSTRAINT FK_SOCIO_PAG_SOCIO
        FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES SOCIO (NUMB_SOCIO_PRINCIPAL)
        ON DELETE CASCADE
);

CREATE INDEX IX_SOCIO_PAG_VENC
    ON SOCIO_PAGAMENTO (NUMB_SOCIO_PRINCIPAL, DATA_VENCIMENTO);

COMMENT ON TABLE SOCIO_PAGAMENTO IS
    'Pagamentos mensais do socio - PE PERIODICO-PAGAMENTO (modelo 1N)';
