-- DBATDP-18: Tabela filha 1N para grupo periódico PERIODICO-PAGAMENTO (sem flatten)

CREATE TABLE TB_SOCIO_PERIODICO_PAGAMENTO (
    NUMB_SOCIO_PRINCIPAL   DECIMAL(9, 0)  NOT NULL,
    SEQ_PERIODICO          INTEGER        NOT NULL,
    DATA_VENCIMENTO        DATE           NOT NULL,
    VALR_MENSALIDADE       DECIMAL(6, 2)  NOT NULL,
    PAGAMENTO_OK           CHAR(1)        NOT NULL DEFAULT 'N',
    CONSTRAINT PK_TB_SOCIO_PERIODICO PRIMARY KEY (NUMB_SOCIO_PRINCIPAL, SEQ_PERIODICO),
    CONSTRAINT FK_TB_SOCIO_PERIODICO_SOCIO
        FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES TB_SOCIO (NUMB_SOCIO_PRINCIPAL)
        ON DELETE CASCADE
);

CREATE INDEX IX_TB_SOCIO_PERIODICO_VENC ON TB_SOCIO_PERIODICO_PAGAMENTO
    (NUMB_SOCIO_PRINCIPAL, DATA_VENCIMENTO);

COMMENT ON TABLE TB_SOCIO_PERIODICO_PAGAMENTO IS
    'Período de pagamento / mensalidade - PE PERIODICO-PAGAMENTO';
