-- DBATDP-17: DDL ADABAS-SOCIOS -> DB2 (entidade SOCIO + PE PERIODICO-PAGAMENTO)
-- SUPER1 (CATG-SOCIO + INDI-DIVIDA): indice composto, sem coluna fisica SUPER

CREATE TABLE ADABAS_SOCIOS (
    NUMB_SOCIO_PRINCIPAL  DECIMAL(9, 0)  NOT NULL,
    NOME_SOCIO_PRINCIPAL  VARCHAR(40)    NOT NULL,
    DATA_CADASTRO         DATE           NOT NULL,
    CATG_SOCIO            SMALLINT       NOT NULL,
    INDI_DIVIDA           CHAR(1)        NOT NULL DEFAULT 'N',
    DATA_BAIXA            DATE,
    HORA_BAIXA            CHAR(5),
    OBSV_SOCIO            VARCHAR(500),
    CONSTRAINT PK_ADABAS_SOCIOS PRIMARY KEY (NUMB_SOCIO_PRINCIPAL)
);

CREATE INDEX IX_ADABAS_SOCIOS_SUPER1
    ON ADABAS_SOCIOS (CATG_SOCIO, INDI_DIVIDA);

CREATE TABLE ADABAS_SOCIOS_PERIODICO_PAGAMENTO (
    NUMB_SOCIO_PRINCIPAL  DECIMAL(9, 0)  NOT NULL,
    SEQ_PERIODICO         SMALLINT       NOT NULL,
    DATA_VENCIMENTO       DATE           NOT NULL,
    VALR_MENSALIDADE      DECIMAL(6, 2)  NOT NULL,
    PAGAMENTO_OK          CHAR(1)        NOT NULL,
    CONSTRAINT PK_ADABAS_SOCIOS_PP PRIMARY KEY (NUMB_SOCIO_PRINCIPAL, SEQ_PERIODICO),
    CONSTRAINT FK_ADABAS_SOCIOS_PP_SOCIO FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES ADABAS_SOCIOS (NUMB_SOCIO_PRINCIPAL)
);
