-- DB2 DDL: SOCIO (parent) and SOCIO_PAGAMENTO (child)
-- Migrated from ADABAS-SOCIOS (DDM FNR 24)
-- PERIODICO-PAGAMENTO converted to relational child table (no flattening)

CREATE TABLE SOCIO (
    NUMB_SOCIO_PRINCIPAL  DECIMAL(9, 0)  NOT NULL,
    NOME_SOCIO_PRINCIPAL  VARCHAR(40)    NOT NULL,
    DATA_CADASTRO         DATE           NOT NULL,
    CATG_SOCIO            SMALLINT       NOT NULL,
    INDI_DIVIDA           CHAR(1)        NOT NULL,
    DATA_BAIXA            DATE,
    HORA_BAIXA            VARCHAR(5),
    OBSV_SOCIO            VARCHAR(500),
    CONSTRAINT PK_SOCIO PRIMARY KEY (NUMB_SOCIO_PRINCIPAL),
    CONSTRAINT CK_SOCIO_INDI_DIVIDA CHECK (INDI_DIVIDA IN ('T', 'F'))
);

-- SUPER1 (CATG-SOCIO + INDI-DIVIDA) represented as composite index, not a physical column
CREATE INDEX IX_SOCIO_SUPER1 ON SOCIO (CATG_SOCIO, INDI_DIVIDA);

CREATE TABLE SOCIO_PAGAMENTO (
    ID_PAGAMENTO          BIGINT         GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NUMB_SOCIO_PRINCIPAL  DECIMAL(9, 0)  NOT NULL,
    DATA_VENCIMENTO       DATE           NOT NULL,
    VALR_MENSALIDADE      DECIMAL(8, 2)  NOT NULL,
    PAGAMENTO_OK          CHAR(1)        NOT NULL,
    CONSTRAINT PK_SOCIO_PAGAMENTO PRIMARY KEY (ID_PAGAMENTO),
    CONSTRAINT FK_SOCIO_PAGAMENTO_SOCIO FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES SOCIO (NUMB_SOCIO_PRINCIPAL) ON DELETE CASCADE,
    CONSTRAINT CK_SOCIO_PAGAMENTO_OK CHECK (PAGAMENTO_OK IN ('T', 'F'))
);

CREATE INDEX IX_SOCIO_PAGAMENTO_SOCIO ON SOCIO_PAGAMENTO (NUMB_SOCIO_PRINCIPAL);
