-- DB2 schema: ADABAS-SOCIOS migration (DBATDP-10)
-- Entity SOCIOS with child SOCIOS_PAGAMENTO (periodic group PERIODICO-PAGAMENTO)

CREATE TABLE SOCIOS (
    NUMB_SOCIO_PRINCIPAL   DECIMAL(9, 0)  NOT NULL,
    NOME_SOCIO_PRINCIPAL   VARCHAR(40)    NOT NULL,
    DATA_CADASTRO          DATE           NOT NULL,
    CATG_SOCIO             SMALLINT       NOT NULL,
    INDI_DIVIDA            CHAR(1)        NOT NULL,
    DATA_BAIXA             DATE,
    HORA_BAIXA             VARCHAR(5),
    OBSV_SOCIO             VARCHAR(500),
    CONSTRAINT PK_SOCIOS PRIMARY KEY (NUMB_SOCIO_PRINCIPAL),
    CONSTRAINT CK_SOCIOS_INDI_DIVIDA CHECK (INDI_DIVIDA IN ('0', '1'))
);

-- SUPER1 (Adabas): index on CATG-SOCIO + INDI-DIVIDA (not a physical column)
CREATE INDEX IX_SOCIOS_SUPER1 ON SOCIOS (CATG_SOCIO, INDI_DIVIDA);

CREATE TABLE SOCIOS_PAGAMENTO (
    ID_PAGAMENTO           BIGINT         GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NUMB_SOCIO_PRINCIPAL   DECIMAL(9, 0)  NOT NULL,
    SEQ_PAGAMENTO          INTEGER        NOT NULL,
    DATA_VENCIMENTO        DATE           NOT NULL,
    VALR_MENSALIDADE       DECIMAL(8, 2)  NOT NULL,
    PAGAMENTO_OK           CHAR(1)        NOT NULL,
    CONSTRAINT PK_SOCIOS_PAGAMENTO PRIMARY KEY (ID_PAGAMENTO),
    CONSTRAINT FK_SOCIOS_PAGAMENTO_SOCIO
        FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES SOCIOS (NUMB_SOCIO_PRINCIPAL)
        ON DELETE CASCADE,
    CONSTRAINT UK_SOCIOS_PAGAMENTO_SEQ
        UNIQUE (NUMB_SOCIO_PRINCIPAL, SEQ_PAGAMENTO),
    CONSTRAINT CK_SOCIOS_PAGAMENTO_OK CHECK (PAGAMENTO_OK IN ('0', '1'))
);

CREATE INDEX IX_SOCIOS_PAGAMENTO_SOCIO ON SOCIOS_PAGAMENTO (NUMB_SOCIO_PRINCIPAL);
