-- DB2 SCRIPT - CRIACAO DE TABELAS PARA MIGRACAO ADABAS SOCIOS
-- DATA: 2026-05-26
-- ORIGEM: ADABAS DDM DBID 0 FNR 24 - ADABAS-SOCIOS

-- CRIAR TABELA PRINCIPAL: SOCIOS
-- Estrutura equivalente aos campos level 1 do ADABAS
CREATE TABLE SOCIOS (
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9,0) NOT NULL PRIMARY KEY,
    NOME_SOCIO_PRINCIPAL    CHAR(40)      NOT NULL,
    DATA_CADASTRO           DATE          NOT NULL,
    CATG_SOCIO              SMALLINT      NOT NULL,
    INDI_DIVIDA             CHAR(1)       NOT NULL,
    DATA_BAIXA              DATE,
    HORA_BAIXA              TIME,
    OBSV_SOCIO              VARCHAR(500)
);

-- CRIAR TABELA FILHA: PERIODICO_PAGAMENTO
-- Equivalente ao grupo periódico P1 AD PERIODICO-PAGAMENTO
-- Relacionamento 1:N com SOCIOS
CREATE TABLE PERIODICO_PAGAMENTO (
    NUMB_SOCIO              DECIMAL(9,0) NOT NULL,
    SEQUENCIA               SMALLINT      NOT NULL,
    DATA_VENCIMENTO         DATE          NOT NULL,
    VALR_MENSALIDADE        DECIMAL(6,2)  NOT NULL,
    PAGAMENTO_OK            CHAR(1)       NOT NULL,
    PRIMARY KEY (NUMB_SOCIO, SEQUENCIA),
    FOREIGN KEY (NUMB_SOCIO) REFERENCES SOCIOS(NUMB_SOCIO_PRINCIPAL)
        ON DELETE CASCADE
);

-- CRIAR INDICE PARA SUPER1
-- Equivalente ao SUPER1 = BA + BB (CATG_SOCIO + INDI_DIVIDA)
CREATE INDEX IDX_SUPER1_SOCIOS
    ON SOCIOS(CATG_SOCIO, INDI_DIVIDA);

-- CRIAR INDICE PARA MELHORAR PERFORMANCE EM BUSCAS
CREATE INDEX IDX_DATA_CADASTRO_SOCIOS
    ON SOCIOS(DATA_CADASTRO);

-- CRIAR INDICE PARA BUSCAS EM PERIÓDICOS
CREATE INDEX IDX_PERIODICO_VENCIMENTO
    ON PERIODICO_PAGAMENTO(NUMB_SOCIO, DATA_VENCIMENTO);

-- TABELA CRIADA COM SUCESSO
-- Notas:
-- - NUMB_SOCIO_PRINCIPAL é chave primária (não permite duplicatas)
-- - PERIODICO_PAGAMENTO tem relacionamento 1:N via foreign key
-- - Índice SUPER1 suporta queries compostas em CATG_SOCIO e INDI_DIVIDA
-- - CASCADE DELETE garante que periódicos sejam removidos com sócio
