-- Criação das tabelas DB2 para migração de ADABAS SOCIOS

-- Tabela principal SOCIOS
CREATE TABLE SOCIOS (
    NUMB_SOCIO_PRINCIPAL DECIMAL(9,0) NOT NULL PRIMARY KEY,
    NOME_SOCIO_PRINCIPAL CHAR(40) NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    CATG_SOCIO SMALLINT NOT NULL,
    INDI_DIVIDA SMALLINT NOT NULL,
    DATA_BAIXA DATE,
    HORA_BAIXA TIME,
    OBSV_SOCIO VARCHAR(500)
);

-- Índice composto equivalente a SUPER1 (BA+BB = CATG-SOCIO+INDI-DIVIDA)
CREATE INDEX IDX_SOCIOS_SUPER1
    ON SOCIOS (CATG_SOCIO, INDI_DIVIDA);

-- Tabela filha para grupo periódico PAGAMENTO
CREATE TABLE SOCIOS_PAGAMENTO (
    NUMB_SOCIO_PRINCIPAL DECIMAL(9,0) NOT NULL,
    SEQ_PAGAMENTO SMALLINT NOT NULL,
    DATA_VENCIMENTO DATE NOT NULL,
    VALR_MENSALIDADE DECIMAL(6,2) NOT NULL,
    PAGAMENTO_OK SMALLINT NOT NULL,
    PRIMARY KEY (NUMB_SOCIO_PRINCIPAL, SEQ_PAGAMENTO),
    FOREIGN KEY (NUMB_SOCIO_PRINCIPAL) REFERENCES SOCIOS(NUMB_SOCIO_PRINCIPAL)
);

-- Índice na tabela filha
CREATE INDEX IDX_SOCIOS_PAGAMENTO_FK
    ON SOCIOS_PAGAMENTO (NUMB_SOCIO_PRINCIPAL);
