-- DBATDP-18: DDL DB2 - Migracao ADABAS-SOCIOS
-- Entidade principal e tabela filha 1:N para grupo periodico PERIODICO-PAGAMENTO
-- SUPER1 (CATG-SOCIO + INDI-DIVIDA) convertida em indice composto, nao coluna fisica

CREATE TABLE TB_SOCIO (
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)   NOT NULL,
    NOME_SOCIO_PRINCIPAL    CHAR(40)        NOT NULL,
    DATA_CADASTRO           DATE,
    CATG_SOCIO              SMALLINT,
    INDI_DIVIDA             CHAR(1),
    DATA_BAIXA              DATE,
    HORA_BAIXA              CHAR(12),
    OBSV_SOCIO              VARCHAR(500),
    CONSTRAINT PK_TB_SOCIO PRIMARY KEY (NUMB_SOCIO_PRINCIPAL)
);

CREATE INDEX IX_TB_SOCIO_SUPER1
    ON TB_SOCIO (CATG_SOCIO, INDI_DIVIDA);

CREATE TABLE TB_SOCIO_PERIODICO_PAGAMENTO (
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)   NOT NULL,
    SEQ_PERIODICO           SMALLINT        NOT NULL,
    DATA_VENCIMENTO         DATE,
    VALR_MENSALIDADE        DECIMAL(6, 2),
    PAGAMENTO_OK            CHAR(1),
    CONSTRAINT PK_TB_SOCIO_PERIODICO_PAGAMENTO
        PRIMARY KEY (NUMB_SOCIO_PRINCIPAL, SEQ_PERIODICO),
    CONSTRAINT FK_TB_SOCIO_PERIODICO_SOCIO
        FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES TB_SOCIO (NUMB_SOCIO_PRINCIPAL)
        ON DELETE CASCADE
);

CREATE INDEX IX_TB_SOCIO_PERIODICO_VENC
    ON TB_SOCIO_PERIODICO_PAGAMENTO (NUMB_SOCIO_PRINCIPAL, DATA_VENCIMENTO);
