-- DBATDP-16: Migracao ADABAS-SOCIOS para DB2
-- Entidade principal + tabela filha 1N para PERIODICO-PAGAMENTO
-- SUPER1 (CATG-SOCIO + INDI-DIVIDA) modelado como indice composto, sem coluna fisica

CREATE TABLE SOCIOS (
    NUMB_SOCIO_PRINCIPAL  DECIMAL(9, 0)  NOT NULL,
    NOME_SOCIO_PRINCIPAL  VARCHAR(40)    NOT NULL,
    DATA_CADASTRO         DATE           NOT NULL,
    CATG_SOCIO            SMALLINT       NOT NULL,
    INDI_DIVIDA           CHAR(1)        NOT NULL DEFAULT 'N',
    DATA_BAIXA            DATE,
    HORA_BAIXA            CHAR(5),
    OBSV_SOCIO            VARCHAR(500),
    CONSTRAINT PK_SOCIOS PRIMARY KEY (NUMB_SOCIO_PRINCIPAL),
    CONSTRAINT CK_SOCIOS_INDI_DIVIDA CHECK (INDI_DIVIDA IN ('Y', 'N'))
);

CREATE INDEX IX_SOCIOS_SUPER1
    ON SOCIOS (CATG_SOCIO, INDI_DIVIDA);

CREATE TABLE SOCIOS_PERIODICO_PAGAMENTO (
    NUMB_SOCIO_PRINCIPAL  DECIMAL(9, 0)  NOT NULL,
    SEQ_PERIODICO         SMALLINT       NOT NULL,
    DATA_VENCIMENTO       DATE           NOT NULL,
    VALR_MENSALIDADE      DECIMAL(6, 2)  NOT NULL,
    PAGAMENTO_OK          CHAR(1)        NOT NULL,
    CONSTRAINT PK_SOCIOS_PERIODICO PRIMARY KEY
        (NUMB_SOCIO_PRINCIPAL, SEQ_PERIODICO),
    CONSTRAINT FK_SOCIOS_PERIODICO_SOCIO FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES SOCIOS (NUMB_SOCIO_PRINCIPAL) ON DELETE CASCADE,
    CONSTRAINT CK_SOCIOS_PERIODICO_PAGAMENTO_OK CHECK (PAGAMENTO_OK IN ('Y', 'N'))
);

CREATE INDEX IX_SOCIOS_PERIODICO_VENCIMENTO
    ON SOCIOS_PERIODICO_PAGAMENTO (NUMB_SOCIO_PRINCIPAL, DATA_VENCIMENTO);
