-- DB2 DDL: SOCIOS (principal) + SOCIOS_PERIODICO (1:N, sem limite artificial de linhas)
-- Compatível com DB2 LUW / Db2 for z/OS (ajustar tipos BOOLEAN se necessário no seu release)

CREATE TABLE SOCIOS (
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)   NOT NULL,
    NOME_SOCIO_PRINCIPAL    VARCHAR(40)     NOT NULL,
    DATA_CADASTRO           DATE            NOT NULL,
    CATG_SOCIO              SMALLINT        NOT NULL,
    DATA_BAIXA              DATE,
    HORA_BAIXA              TIME,
    OBSV_SOCIO              VARCHAR(500)    NOT NULL,
    INDI_DIVIDA             SMALLINT        NOT NULL DEFAULT 0,
    CONSTRAINT PK_SOCIOS PRIMARY KEY (NUMB_SOCIO_PRINCIPAL)
);

CREATE INDEX IX_SOCIOS_CATG ON SOCIOS (CATG_SOCIO);

CREATE TABLE SOCIOS_PERIODICO (
    PERIODICO_ID            BIGINT          NOT NULL GENERATED ALWAYS AS IDENTITY,
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)   NOT NULL,
    DATA_VENCIMENTO         DATE            NOT NULL,
    VALR_MENSALIDADE        DECIMAL(12, 2)  NOT NULL,
    PAGAMENTO_OK            SMALLINT        NOT NULL,
    CONSTRAINT PK_SOCIOS_PERIODICO PRIMARY KEY (PERIODICO_ID),
    CONSTRAINT FK_SOCIOS_PERIODICO_SOCIO
        FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES SOCIOS (NUMB_SOCIO_PRINCIPAL)
        ON DELETE CASCADE,
    CONSTRAINT CK_SOCIOS_PERIODICO_PAG
        CHECK (PAGAMENTO_OK IN (0, 1))
);

CREATE INDEX IX_SOCIOS_PERIODICO_SOCIO ON SOCIOS_PERIODICO (NUMB_SOCIO_PRINCIPAL);

COMMENT ON TABLE SOCIOS IS 'Sócio principal (ex-ADABAS SOCIOS)';
COMMENT ON TABLE SOCIOS_PERIODICO IS 'Mensalidades / grupo periódico 1:N (sem flatten; linhas ilimitadas)';
COMMENT ON COLUMN SOCIOS_PERIODICO.PAGAMENTO_OK IS '0=FALSE, 1=TRUE (BOOLEAN lógico)';
