-- DB2 DDL: sócio (parent) and periodic payment rows (normalized from ADABAS PERIODICO-PAGAMENTO)
-- Issue DBATDP-1: Migração ADABAS/DB2

CREATE TABLE SOCIO (
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)   NOT NULL,
    NOME_SOCIO_PRINCIPAL    VARCHAR(40)    NOT NULL,
    DATA_CADASTRO           DATE           NOT NULL,
    CATG_SOCIO              SMALLINT       NOT NULL,
    INDI_DIVIDA             SMALLINT       NOT NULL DEFAULT 0,
    DATA_BAIXA              DATE,
    HORA_BAIXA              CHAR(12),
    OBSV_SOCIO              VARCHAR(500)   NOT NULL,
    CONSTRAINT PK_SOCIO PRIMARY KEY (NUMB_SOCIO_PRINCIPAL)
);

CREATE TABLE SOCIO_PAGAMENTO (
    ID_SOCIO_PAGAMENTO      BIGINT         NOT NULL GENERATED ALWAYS AS IDENTITY,
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)  NOT NULL,
    NR_PARCELA              SMALLINT       NOT NULL,
    DATA_VENCIMENTO         DATE           NOT NULL,
    VALR_MENSALIDADE        DECIMAL(8, 2)  NOT NULL,
    PAGAMENTO_OK            CHAR(1)        NOT NULL,
    CONSTRAINT PK_SOCIO_PAGAMENTO PRIMARY KEY (ID_SOCIO_PAGAMENTO),
    CONSTRAINT FK_SOCIO_PAGAMENTO_SOCIO FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES SOCIO (NUMB_SOCIO_PRINCIPAL) ON DELETE CASCADE,
    CONSTRAINT UQ_SOCIO_PAGAMENTO_PARCELA UNIQUE (NUMB_SOCIO_PRINCIPAL, NR_PARCELA)
);

CREATE INDEX IX_SOCIO_PAGAMENTO_SOCIO ON SOCIO_PAGAMENTO (NUMB_SOCIO_PRINCIPAL);
