-- DDL DB2 - Entidade SOCIO (migracao ADABAS-SOCIOS-P2)
-- SUPER1 (CATG-SOCIO + INDI-DIVIDA) representado por indice composto, nao como coluna fisica.

CREATE TABLE SOCIO (
    NUMB_SOCIO_PRINCIPAL   DECIMAL(9, 0)  NOT NULL,
    NOME_SOCIO_PRINCIPAL   VARCHAR(40)    NOT NULL,
    DATA_CADASTRO          DATE           NOT NULL,
    CATG_SOCIO             SMALLINT       NOT NULL,
    INDI_DIVIDA            CHAR(1)        NOT NULL DEFAULT 'N',
    DATA_BAIXA             DATE,
    HORA_BAIXA             CHAR(5),
    OBSV_SOCIO             VARCHAR(500),
    CONSTRAINT PK_SOCIO PRIMARY KEY (NUMB_SOCIO_PRINCIPAL)
);

CREATE INDEX IX_SOCIO_SUPER1
    ON SOCIO (CATG_SOCIO, INDI_DIVIDA);

COMMENT ON TABLE SOCIO IS
    'Cadastro principal de socios - migrado de ADABAS-SOCIOS';

-- Grupo periódico PERIODICO-PAGAMENTO -> tabela filha 1N (sem limite artificial de ocorrencias)
CREATE TABLE SOCIO_PERIODICO_PAGAMENTO (
    SOCIO_PERIODICO_ID     BIGINT         GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NUMB_SOCIO_PRINCIPAL   DECIMAL(9, 0)  NOT NULL,
    SEQ_OCORRENCIA         INTEGER        NOT NULL,
    DATA_VENCIMENTO        DATE           NOT NULL,
    VALR_MENSALIDADE       DECIMAL(8, 2)  NOT NULL,
    PAGAMENTO_OK           CHAR(1)        NOT NULL DEFAULT 'N',
    CONSTRAINT PK_SOCIO_PERIODICO PRIMARY KEY (SOCIO_PERIODICO_ID),
    CONSTRAINT UQ_SOCIO_PERIODICO_SEQ UNIQUE (NUMB_SOCIO_PRINCIPAL, SEQ_OCORRENCIA),
    CONSTRAINT FK_SOCIO_PERIODICO_SOCIO
        FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES SOCIO (NUMB_SOCIO_PRINCIPAL)
        ON DELETE CASCADE
);

CREATE INDEX IX_SOCIO_PERIODICO_SOCIO
    ON SOCIO_PERIODICO_PAGAMENTO (NUMB_SOCIO_PRINCIPAL);

COMMENT ON TABLE SOCIO_PERIODICO_PAGAMENTO IS
    'Pagamentos periodicos do socio - migrado de PE PERIODICO-PAGAMENTO';
