-- DBATDP-14: Migração ADABAS SOCIOS -> DB2
-- Tabelas SOCIO (principal) e SOCIO_PAGAMENTO (grupo periódico PERIODICO-PAGAMENTO)

CREATE TABLE SOCIO (
    NUMB_SOCIO_PRINCIPAL   DECIMAL(9, 0)  NOT NULL,
    NOME_SOCIO_PRINCIPAL   VARCHAR(40)    NOT NULL,
    DATA_CADASTRO          DATE           NOT NULL,
    CATG_SOCIO             SMALLINT       NOT NULL,
    INDI_DIVIDA            CHAR(1)        NOT NULL DEFAULT 'N',
    DATA_BAIXA             DATE,
    HORA_BAIXA             CHAR(5),
    OBSV_SOCIO             VARCHAR(500),
    CONSTRAINT PK_SOCIO PRIMARY KEY (NUMB_SOCIO_PRINCIPAL),
    CONSTRAINT CK_SOCIO_INDI_DIVIDA CHECK (INDI_DIVIDA IN ('Y', 'N'))
);

-- Índice equivalente ao SUPER1 (CATG-SOCIO + INDI-DIVIDA)
CREATE INDEX IX_SOCIO_SUPER1 ON SOCIO (CATG_SOCIO, INDI_DIVIDA);

CREATE TABLE SOCIO_PAGAMENTO (
    ID_SOCIO_PAGAMENTO     BIGINT         GENERATED ALWAYS AS IDENTITY,
    NUMB_SOCIO_PRINCIPAL   DECIMAL(9, 0)  NOT NULL,
    SEQ_PAGAMENTO          SMALLINT       NOT NULL,
    DATA_VENCIMENTO        DATE           NOT NULL,
    VALR_MENSALIDADE       DECIMAL(6, 2)  NOT NULL,
    PAGAMENTO_OK           CHAR(1)        NOT NULL DEFAULT 'N',
    CONSTRAINT PK_SOCIO_PAGAMENTO PRIMARY KEY (ID_SOCIO_PAGAMENTO),
    CONSTRAINT FK_SOCIO_PAG_SOCIO FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES SOCIO (NUMB_SOCIO_PRINCIPAL),
    CONSTRAINT UK_SOCIO_PAG_SEQ UNIQUE (NUMB_SOCIO_PRINCIPAL, SEQ_PAGAMENTO),
    CONSTRAINT CK_SOCIO_PAG_OK CHECK (PAGAMENTO_OK IN ('Y', 'N'))
);

CREATE INDEX IX_SOCIO_PAG_NUMB ON SOCIO_PAGAMENTO (NUMB_SOCIO_PRINCIPAL);
