-- DBATDP-18: Migração ADABAS-SOCIOS (P2) para DB2
-- Entidade: sócios com pagamentos periódicos (PERIODICO-PAGAMENTO -> SOCIO_PAGAMENTO 1:N)
-- SUPER1 (CATG-SOCIO + INDI-DIVIDA): índice composto, sem coluna física SUPER

CREATE TABLE SOCIO (
    NUMB_SOCIO_PRINCIPAL  DECIMAL(9, 0)  NOT NULL,
    NOME_SOCIO_PRINCIPAL  VARCHAR(40)    NOT NULL,
    DATA_CADASTRO         DATE           NOT NULL,
    CATG_SOCIO            SMALLINT       NOT NULL,
    INDI_DIVIDA           CHAR(1)        NOT NULL DEFAULT 'N',
    DATA_BAIXA            DATE,
    HORA_BAIXA            CHAR(5),
    OBSV_SOCIO            VARCHAR(500),
    CONSTRAINT PK_SOCIO PRIMARY KEY (NUMB_SOCIO_PRINCIPAL)
);

-- Equivalente funcional à SUPER1 do ADABAS (BA+BB: CATG-SOCIO + INDI-DIVIDA)
CREATE INDEX IX_SOCIO_SUPER1 ON SOCIO (CATG_SOCIO, INDI_DIVIDA);

CREATE TABLE SOCIO_PAGAMENTO (
    NUMB_SOCIO_PRINCIPAL  DECIMAL(9, 0)  NOT NULL,
    SEQ_PAGAMENTO         SMALLINT       NOT NULL,
    DATA_VENCIMENTO       DATE           NOT NULL,
    VALR_MENSALIDADE      DECIMAL(8, 2)  NOT NULL,
    PAGAMENTO_OK          CHAR(1)        NOT NULL,
    CONSTRAINT PK_SOCIO_PAGAMENTO PRIMARY KEY (NUMB_SOCIO_PRINCIPAL, SEQ_PAGAMENTO),
    CONSTRAINT FK_SOCIO_PAG_SOCIO FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES SOCIO (NUMB_SOCIO_PRINCIPAL)
);

CREATE INDEX IX_SOCIO_PAG_VENC ON SOCIO_PAGAMENTO (NUMB_SOCIO_PRINCIPAL, DATA_VENCIMENTO);
