-- DBATDP-1: DB2 relational model for sócio (member) data.
-- Periodic group PERIODICO-PAGAMENTO is normalized to SOCIO_PAGAMENTO (1:N).

CREATE TABLE SOCIO (
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)   NOT NULL,
    NOME_SOCIO_PRINCIPAL    VARCHAR(40)     NOT NULL,
    DATA_CADASTRO           DATE            NOT NULL,
    CATG_SOCIO              SMALLINT        NOT NULL,
    INDI_DIVIDA             CHAR(1)         NOT NULL,
    DATA_BAIXA              DATE,
    HORA_BAIXA              VARCHAR(12),
    OBSV_CLIENTE            VARCHAR(500)    NOT NULL,
    SUPER1                  VARCHAR(20),
    CONSTRAINT PK_SOCIO PRIMARY KEY (NUMB_SOCIO_PRINCIPAL)
);

CREATE TABLE SOCIO_PAGAMENTO (
    SOCIO_PAGAMENTO_ID    BIGINT          NOT NULL
        GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)   NOT NULL,
    SEQ_MENSALIDADE         SMALLINT        NOT NULL,
    DATA_VENCIMENTO         DATE            NOT NULL,
    VALR_MENSALIDADE        DECIMAL(8, 2)   NOT NULL,
    PAGAMENTO_OK            CHAR(1)         NOT NULL,
    CONSTRAINT PK_SOCIO_PAGAMENTO PRIMARY KEY (SOCIO_PAGAMENTO_ID),
    CONSTRAINT FK_SP_SOCIO FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES SOCIO (NUMB_SOCIO_PRINCIPAL) ON DELETE CASCADE,
    CONSTRAINT UQ_SP_SOCIO_SEQ UNIQUE (NUMB_SOCIO_PRINCIPAL, SEQ_MENSALIDADE)
);

CREATE INDEX IX_SP_SOCIO ON SOCIO_PAGAMENTO (NUMB_SOCIO_PRINCIPAL);
