-- DB2 Table Schema for SOCIOS migration from ADABAS
-- Created: 2026-05-15
-- Purpose: Replace ADABAS SOCIOS structure with normalized DB2 tables

-- Main SOCIOS table (members)
CREATE TABLE SOCIOS (
    NUMB_SOCIO_PRINCIPAL DECIMAL(9,0) NOT NULL PRIMARY KEY,
    NOME_SOCIO_PRINCIPAL CHAR(40) NOT NULL,
    DATA_CADASTRO DATE NOT NULL,
    CATG_SOCIO SMALLINT,
    DATA_BAIXA DATE,
    HORA_BAIXA TIME,
    OBSV_SOCIO VARCHAR(500)
) IN TABLESPACE TBSP01;

-- Child table for periodic payments (1N relationship)
-- Replaces ADABAS periodic group PERIODICO-PAGAMENTO
CREATE TABLE SOCIOS_PAGAMENTO (
    ID_PAGAMENTO INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY
        (START WITH 1 INCREMENT BY 1),
    NUMB_SOCIO_PRINCIPAL DECIMAL(9,0) NOT NULL,
    DATA_VENCIMENTO DATE NOT NULL,
    VALR_MENSALIDADE DECIMAL(6,2),
    PAGAMENTO_OK CHAR(1),
    PRIMARY KEY (ID_PAGAMENTO),
    FOREIGN KEY (NUMB_SOCIO_PRINCIPAL) REFERENCES SOCIOS(NUMB_SOCIO_PRINCIPAL)
        ON DELETE CASCADE
) IN TABLESPACE TBSP01;

-- Index for efficient payment lookups by member
CREATE INDEX IDX_SOCIOS_PAGAMENTO_MEMBRO
    ON SOCIOS_PAGAMENTO(NUMB_SOCIO_PRINCIPAL);
