-- SOCIOS / SOCIOS_PAGAMENTOS — migração ADABAS ADABAS-SOCIOS (DBATDP-8)
-- Mapeamento: NUMB-SOCIO-PRINCIPAL (N 9,0) → NUMB_SOCIO_PRINCIPAL PK
--             NOME-SOCIO-PRINCIPAL (C 40) → NOME_SOCIO_PRINCIPAL
--             DATA-CADASTRO (D 6) → DATA_CADASTRO (DATE, conversão YYMMDD/ISO no COBOL)
--             CATG-SOCIO (I 2) → CATG_SOCIO
--             DATA-BAIXA (D 6, nulo) → DATA_BAIXA
--             HORA-BAIXA (T 12, nulo) → HORA_BAIXA (VARCHAR, HH:MM conforme regra)
--             OBSV-SOCIO (A 500) → OBSV_SOCIO
-- Grupo periódico PERIODICO-PAGAMENTO → SOCIOS_PAGAMENTOS (1N, sem limite artificial)

CREATE TABLE SOCIOS (
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)   NOT NULL,
    NOME_SOCIO_PRINCIPAL    VARCHAR(40)     NOT NULL,
    DATA_CADASTRO           DATE            NOT NULL,
    CATG_SOCIO              SMALLINT        NOT NULL,
    DATA_BAIXA              DATE,
    HORA_BAIXA              VARCHAR(8),
    OBSV_SOCIO              VARCHAR(500)    NOT NULL,
    CONSTRAINT PK_SOCIOS PRIMARY KEY (NUMB_SOCIO_PRINCIPAL),
    CONSTRAINT CK_SOCIOS_CATG CHECK (CATG_SOCIO IN (1, 2))
);

CREATE TABLE SOCIOS_PAGAMENTOS (
    ID_PAGAMENTO            BIGINT          NOT NULL GENERATED ALWAYS AS IDENTITY,
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)   NOT NULL,
    SEQ_ORDEM               SMALLINT        NOT NULL,
    DATA_VENCIMENTO         DATE            NOT NULL,
    VALR_MENSALIDADE        DECIMAL(11, 2)  NOT NULL,
    PAGAMENTO_OK            CHAR(1)         NOT NULL,
    CONSTRAINT PK_SOCIOS_PAGAMENTOS PRIMARY KEY (ID_PAGAMENTO),
    CONSTRAINT FK_SOCIOS_PAG_SOCIOS FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES SOCIOS (NUMB_SOCIO_PRINCIPAL) ON DELETE CASCADE,
    CONSTRAINT CK_SOCIOS_PAG_OK CHECK (PAGAMENTO_OK IN ('Y', 'N')),
    CONSTRAINT UK_SOCIOS_PAG_SEQ UNIQUE (NUMB_SOCIO_PRINCIPAL, SEQ_ORDEM)
);

CREATE INDEX IX_SOCIOS_PAG_SOCIO ON SOCIOS_PAGAMENTOS (NUMB_SOCIO_PRINCIPAL);

COMMENT ON TABLE SOCIOS IS 'Sócio principal — campos escalares migrados de ADABAS-SOCIOS';
COMMENT ON TABLE SOCIOS_PAGAMENTOS IS 'Mensalidades normalizadas (ex-PERIODICO-PAGAMENTO), crescimento ilimitado';
