-- DB2 DDL: SOCIO (mestre) + SOCIO_PAGAMENTO (1:N) — DBATDP-9
-- Conversao ADABAS-SOCIOS / grupo PERIODICO-PAGAMENTO

CREATE TABLE SOCIO (
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)  NOT NULL,
    NOME_SOCIO_PRINCIPAL    VARCHAR(40)    NOT NULL,
    DATA_CADASTRO           DATE           NOT NULL,
    CATG_SOCIO              SMALLINT       NOT NULL,
    INDI_DIVIDA             SMALLINT       NOT NULL DEFAULT 0,
    DATA_BAIXA              DATE,
    HORA_BAIXA              TIME,
    OBSV_CLIENTE            VARCHAR(500)   NOT NULL,
    SUPER1                  VARCHAR(20),
    CONSTRAINT PK_SOCIO PRIMARY KEY (NUMB_SOCIO_PRINCIPAL)
);

CREATE TABLE SOCIO_PAGAMENTO (
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)  NOT NULL,
    NUM_PARCELA             SMALLINT       NOT NULL,
    DATA_VENCIMENTO         DATE           NOT NULL,
    VALR_MENSALIDADE        DECIMAL(8, 2)  NOT NULL,
    PAGAMENTO_OK            CHAR(1)        NOT NULL,
    CONSTRAINT PK_SOCIO_PAGAMENTO
        PRIMARY KEY (NUMB_SOCIO_PRINCIPAL, NUM_PARCELA),
    CONSTRAINT FK_SOCIO_PAG_SOCIO
        FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES SOCIO (NUMB_SOCIO_PRINCIPAL)
        ON DELETE CASCADE
);

CREATE INDEX IX_SOCIO_PAGAMENTO_VENC
    ON SOCIO_PAGAMENTO (DATA_VENCIMENTO);
