-- DB2 physical model for cadastro de sócios (fase 2)
-- Periodic group PERIODICO-PAGAMENTO -> child table 1:N (unbounded rows).

CREATE TABLE SOCIO (
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)   NOT NULL,
    NOME_SOCIO_PRINCIPAL    VARCHAR(40)     NOT NULL,
    DATA_CADASTRO           DATE            NOT NULL,
    CATG_SOCIO              SMALLINT        NOT NULL,
    INDI_DIVIDA             CHAR(1)         NOT NULL,
    DATA_BAIXA              DATE,
    HORA_BAIXA              VARCHAR(12),
    OBSV_CLIENTE            VARCHAR(500)    NOT NULL,
    CONSTRAINT PK_SOCIO PRIMARY KEY (NUMB_SOCIO_PRINCIPAL)
);

CREATE TABLE SOCIO_PAGAMENTO (
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)   NOT NULL,
    SEQ_PAGAMENTO           INTEGER         NOT NULL,
    DATA_VENCIMENTO         DATE            NOT NULL,
    VALR_MENSALIDADE        DECIMAL(8, 2)   NOT NULL,
    PAGAMENTO_OK            CHAR(1)         NOT NULL,
    CONSTRAINT PK_SOCIO_PAG
        PRIMARY KEY (NUMB_SOCIO_PRINCIPAL, SEQ_PAGAMENTO),
    CONSTRAINT FK_SOCIO_PAG_SOCIO
        FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES SOCIO (NUMB_SOCIO_PRINCIPAL)
        ON DELETE CASCADE
);

CREATE INDEX IX_SOCIO_PAG_SOCIO
    ON SOCIO_PAGAMENTO (NUMB_SOCIO_PRINCIPAL);
