-- DB2 Table Creation Script for SOCIOS Migration
-- Created for DBATDP-2: Migração Adabas/Cobol/DB2
-- Parent and child tables with normalized periodic group handling

CREATE TABLE SOCIOS (
  NUMB_SOCIO_PRINCIPAL  DECIMAL(9,0)   NOT NULL,
  NOME_SOCIO_PRINCIPAL  CHAR(40)       NOT NULL,
  DATA_CADASTRO         DATE           NOT NULL,
  CATG_SOCIO            SMALLINT       NOT NULL,
  INDI_DIVIDA           SMALLINT       NOT NULL DEFAULT 0,
  DATA_BAIXA            DATE,
  HORA_BAIXA            CHAR(12),
  OBSV_SOCIO            VARCHAR(500),
  PRIMARY KEY (NUMB_SOCIO_PRINCIPAL)
);

CREATE TABLE SOCIOS_PAGAMENTO (
  SOCIOS_PAGAMENTO_ID   INTEGER        NOT NULL GENERATED ALWAYS AS IDENTITY,
  SOCIO_ID              DECIMAL(9,0)   NOT NULL,
  DATA_VENCIMENTO       DATE           NOT NULL,
  VALR_MENSALIDADE      DECIMAL(6,2)   NOT NULL,
  PAGAMENTO_OK          CHAR(1)        NOT NULL DEFAULT 'F',
  PRIMARY KEY (SOCIOS_PAGAMENTO_ID),
  FOREIGN KEY (SOCIO_ID) REFERENCES SOCIOS(NUMB_SOCIO_PRINCIPAL)
);
