-- DB2 DDL: ADABAS-SOCIOS migration (DBATDP-13)
-- Main entity + normalized periodic group (PERIODICO-PAGAMENTO)
-- SUPER1 (CATG-SOCIO + INDI-DIVIDA) represented as composite index, not a column

CREATE TABLE STF_SOCIO (
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)  NOT NULL,
    NOME_SOCIO_PRINCIPAL    VARCHAR(40)    NOT NULL,
    DATA_CADASTRO           DATE           NOT NULL,
    CATG_SOCIO              SMALLINT       NOT NULL,
    INDI_DIVIDA             CHAR(1)        NOT NULL DEFAULT 'N',
    DATA_BAIXA              DATE,
    HORA_BAIXA              TIME,
    OBSV_SOCIO              VARCHAR(500),
    CONSTRAINT PK_STF_SOCIO PRIMARY KEY (NUMB_SOCIO_PRINCIPAL),
    CONSTRAINT CK_STF_SOCIO_INDI_DIVIDA CHECK (INDI_DIVIDA IN ('Y', 'N')),
    CONSTRAINT CK_STF_SOCIO_CATG_SOCIO CHECK (CATG_SOCIO IN (1, 2))
);

CREATE TABLE STF_SOCIO_PER_PAGTO (
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)  NOT NULL,
    SEQ_PERIODO             INTEGER        NOT NULL,
    DATA_VENCIMENTO         DATE           NOT NULL,
    VALR_MENSALIDADE        DECIMAL(6, 2)  NOT NULL,
    PAGAMENTO_OK            CHAR(1)        NOT NULL DEFAULT 'N',
    CONSTRAINT PK_STF_SOCIO_PER_PAGTO PRIMARY KEY (NUMB_SOCIO_PRINCIPAL, SEQ_PERIODO),
    CONSTRAINT FK_STF_SOCIO_PER_PAGTO_SOCIO FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES STF_SOCIO (NUMB_SOCIO_PRINCIPAL) ON DELETE CASCADE,
    CONSTRAINT CK_STF_SOCIO_PER_PAGTO_OK CHECK (PAGAMENTO_OK IN ('Y', 'N'))
);

-- SUPER1 equivalent: composite access path (CATG-SOCIO + INDI-DIVIDA)
CREATE INDEX IX_STF_SOCIO_SUPER1
    ON STF_SOCIO (CATG_SOCIO, INDI_DIVIDA);

CREATE INDEX IX_STF_SOCIO_PER_PAGTO_VENC
    ON STF_SOCIO_PER_PAGTO (NUMB_SOCIO_PRINCIPAL, DATA_VENCIMENTO);
