-- DB2 DDL derived from ADABAS-SOCIOS / NATURAL-P2 (DBATDP-1).
-- Periodic group PERIODICO-PAGAMENTO is modeled as child rows (1:N), not flattened.

CREATE TABLE T_ADABAS_SOCIOS (
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)  NOT NULL,
    NOME_SOCIO_PRINCIPAL    VARCHAR(40)    NOT NULL,
    DATA_CADASTRO           DATE           NOT NULL,
    CATG_SOCIO              SMALLINT       NOT NULL,
    INDI_DIVIDA             CHAR(1)        NOT NULL DEFAULT 'N',
    DATA_BAIXA              DATE,
    HORA_BAIXA              VARCHAR(12),
    OBSV_SOCIO              VARCHAR(500)   NOT NULL DEFAULT ' ',
    SUPER1                  VARCHAR(50),
    CONSTRAINT PK_T_ADABAS_SOCIOS PRIMARY KEY (NUMB_SOCIO_PRINCIPAL),
    CONSTRAINT CK_T_ADABAS_SOCIOS_CATG CHECK (CATG_SOCIO IN (1, 2)),
    CONSTRAINT CK_T_ADABAS_SOCIOS_INDI CHECK (INDI_DIVIDA IN ('Y', 'N', ' '))
);

CREATE TABLE T_ADABAS_SOCIOS_PAGT (
    ID_PAGAMENTO            BIGINT         NOT NULL GENERATED ALWAYS AS IDENTITY,
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)  NOT NULL,
    DATA_VENCIMENTO         DATE           NOT NULL,
    VALR_MENSALIDADE        DECIMAL(8, 2)  NOT NULL,
    PAGAMENTO_OK            CHAR(1)        NOT NULL,
    CONSTRAINT PK_T_ADABAS_SOCIOS_PAGT PRIMARY KEY (ID_PAGAMENTO),
    CONSTRAINT FK_T_ADABAS_SOCIOS_PAGT_SOC FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES T_ADABAS_SOCIOS (NUMB_SOCIO_PRINCIPAL) ON DELETE CASCADE,
    CONSTRAINT CK_T_ADABAS_SOCIOS_PAGT_OK CHECK (PAGAMENTO_OK IN ('Y', 'N'))
);

CREATE INDEX IX_T_ADABAS_SOCIOS_PAGT_SOC
    ON T_ADABAS_SOCIOS_PAGT (NUMB_SOCIO_PRINCIPAL, DATA_VENCIMENTO);

COMMENT ON TABLE T_ADABAS_SOCIOS IS
    'Cadastro principal de sócios (ex-view ADABAS-SOCIOS nível 1).';
COMMENT ON TABLE T_ADABAS_SOCIOS_PAGT IS
    'Mensalidades / vencimentos (ex-grupo periódico PERIODICO-PAGAMENTO).';
