-- DBATDP-17: DDL DB2 - migracao ADABAS-SOCIOS
-- SUPER1 (CATG-SOCIO + INDI-DIVIDA) -> indice composto, sem coluna fisica

CREATE TABLE TB_SOCIO (
    NUMB_SOCIO_PRINCIPAL   DECIMAL(9, 0)  NOT NULL,
    NOME_SOCIO_PRINCIPAL   VARCHAR(40)    NOT NULL,
    DATA_CADASTRO          DATE           NOT NULL,
    CATG_SOCIO             SMALLINT       NOT NULL,
    INDI_DIVIDA            CHAR(1)        NOT NULL,
    DATA_BAIXA             DATE,
    HORA_BAIXA             CHAR(12),
    OBSV_SOCIO             VARCHAR(500),
    CONSTRAINT PK_TB_SOCIO PRIMARY KEY (NUMB_SOCIO_PRINCIPAL)
);

CREATE INDEX IDX_SOCIO_SUPER1
    ON TB_SOCIO (CATG_SOCIO, INDI_DIVIDA);

CREATE TABLE TB_SOCIO_PERIODICO_PAGAMENTO (
    NUMB_SOCIO_PRINCIPAL   DECIMAL(9, 0)  NOT NULL,
    SEQ_PERIODICO          INTEGER        NOT NULL,
    DATA_VENCIMENTO        DATE           NOT NULL,
    VALR_MENSALIDADE       DECIMAL(6, 2)  NOT NULL,
    PAGAMENTO_OK           CHAR(1)        NOT NULL,
    CONSTRAINT PK_TB_SOCIO_PERIODICO PRIMARY KEY
        (NUMB_SOCIO_PRINCIPAL, SEQ_PERIODICO),
    CONSTRAINT FK_SOCIO_PERIODICO_SOCIO FOREIGN KEY
        (NUMB_SOCIO_PRINCIPAL)
        REFERENCES TB_SOCIO (NUMB_SOCIO_PRINCIPAL)
);

CREATE INDEX IDX_SOCIO_PERIODICO_VENC
    ON TB_SOCIO_PERIODICO_PAGAMENTO
       (NUMB_SOCIO_PRINCIPAL, DATA_VENCIMENTO);
