-- TB_SOCIO / TB_SOCIO_PAGAMENTO_PERIODICO
-- DB2 relational model for sócio (member) and periodic payment lines (PE group),
-- aligned with prg-natural-p2/NATURAL-P2.txt and ADABAS-SOCIOS-P2.txt.
-- Dates stored as DATE (ISO); application uses YYYY-MM-DD host strings.

CREATE TABLE TB_SOCIO (
    SOCIO_RG                DECIMAL(9, 0)  NOT NULL,
    SOCIO_NOME              VARCHAR(40)    NOT NULL,
    DATA_CADASTRO           DATE           NOT NULL,
    CATG_SOCIO              SMALLINT       NOT NULL,
    INDI_DIVIDA             SMALLINT       NOT NULL DEFAULT 0,
    DATA_BAIXA              DATE,
    HORA_BAIXA              VARCHAR(12),
    OBSV_CLIENTE            VARCHAR(500)   NOT NULL,
    SUPER1                  VARCHAR(80),
    CONSTRAINT PK_TB_SOCIO PRIMARY KEY (SOCIO_RG),
    CONSTRAINT CK_TB_SOCIO_CATG CHECK (CATG_SOCIO IN (1, 2))
);

CREATE TABLE TB_SOCIO_PAGAMENTO_PERIODICO (
    PAGAMENTO_ID            BIGINT         NOT NULL GENERATED ALWAYS AS IDENTITY,
    SOCIO_RG                DECIMAL(9, 0)  NOT NULL,
    SEQ_PERIODO             SMALLINT       NOT NULL,
    DATA_VENCIMENTO         DATE           NOT NULL,
    VALR_MENSALIDADE        DECIMAL(8, 2)  NOT NULL,
    PAGAMENTO_OK            CHAR(1)        NOT NULL,
    CONSTRAINT PK_TB_SOCIO_PP PRIMARY KEY (PAGAMENTO_ID),
    CONSTRAINT FK_TB_SOCIO_PP_SOCIO FOREIGN KEY (SOCIO_RG)
        REFERENCES TB_SOCIO (SOCIO_RG) ON DELETE CASCADE,
    CONSTRAINT UK_TB_SOCIO_PP_SEQ UNIQUE (SOCIO_RG, SEQ_PERIODO),
    CONSTRAINT CK_TB_SOCIO_PP_SEQ CHECK (SEQ_PERIODO BETWEEN 1 AND 12),
    CONSTRAINT CK_TB_SOCIO_PP_OK CHECK (PAGAMENTO_OK IN ('Y', 'N'))
);

CREATE INDEX IX_TB_SOCIO_NOME ON TB_SOCIO (SOCIO_NOME);
