-- DB2 DDL: periodic payment lines (child of TB_SOCIO_MEMBRO).
-- One row per period; unlimited rows (no artificial cap vs. legacy 12).

CREATE TABLE TB_SOCIO_PAGAMENTO_PERIODICO (
    ID_PAGAMENTO_PERIODICO  BIGINT         NOT NULL GENERATED ALWAYS AS IDENTITY,
    NUMB_SOCIO_PRINCIPAL    DECIMAL(9, 0)  NOT NULL,
    DATA_VENCIMENTO         DATE           NOT NULL,
    VALR_MENSALIDADE        DECIMAL(8, 2)  NOT NULL,
    PAGAMENTO_OK            CHAR(1)        NOT NULL,
    CONSTRAINT PK_PAG_PERIOD PRIMARY KEY (ID_PAGAMENTO_PERIODICO),
    CONSTRAINT FK_PAG_SOCIO FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES TB_SOCIO_MEMBRO (NUMB_SOCIO_PRINCIPAL)
        ON DELETE CASCADE,
    CONSTRAINT CK_PAG_OK CHECK (PAGAMENTO_OK IN ('T', 'F'))
);

CREATE INDEX IX_PAG_PER_SOCIO ON TB_SOCIO_PAGAMENTO_PERIODICO (NUMB_SOCIO_PRINCIPAL);

COMMENT ON TABLE TB_SOCIO_PAGAMENTO_PERIODICO IS 'Grupo periódico de pagamento — filho 1:N de TB_SOCIO_MEMBRO';
