-- DB2 DDL - ADABAS-SOCIOS migration (DBATDP-18)
-- Periodic group PERIODICO-PAGAMENTO modeled as child table 1:N
-- SUPER1 (CATG-SOCIO + INDI-DIVIDA) not migrated as physical column

CREATE TABLE TB_SOCIO (
    NUMB_SOCIO_PRINCIPAL   DECIMAL(9, 0)  NOT NULL,
    NOME_SOCIO_PRINCIPAL   VARCHAR(40)    NOT NULL,
    DATA_CADASTRO          DATE           NOT NULL,
    CATG_SOCIO             SMALLINT       NOT NULL,
    INDI_DIVIDA            CHAR(1)        NOT NULL DEFAULT 'F',
    DATA_BAIXA             DATE,
    HORA_BAIXA             CHAR(8),
    OBSV_SOCIO             VARCHAR(500),
    CONSTRAINT PK_TB_SOCIO PRIMARY KEY (NUMB_SOCIO_PRINCIPAL)
);

CREATE INDEX IX_TB_SOCIO_SUPER1
    ON TB_SOCIO (CATG_SOCIO, INDI_DIVIDA);

CREATE TABLE TB_SOCIO_PERIODICO_PAGAMENTO (
    NUMB_SOCIO_PRINCIPAL   DECIMAL(9, 0)  NOT NULL,
    SEQ_PERIODO            SMALLINT       NOT NULL,
    DATA_VENCIMENTO        DATE           NOT NULL,
    VALR_MENSALIDADE       DECIMAL(6, 2)  NOT NULL,
    PAGAMENTO_OK           CHAR(1)        NOT NULL DEFAULT 'F',
    CONSTRAINT PK_TB_SOCIO_PERIODICO_PAGAMENTO
        PRIMARY KEY (NUMB_SOCIO_PRINCIPAL, SEQ_PERIODO),
    CONSTRAINT FK_TB_SOCIO_PERIODICO_SOCIO
        FOREIGN KEY (NUMB_SOCIO_PRINCIPAL)
        REFERENCES TB_SOCIO (NUMB_SOCIO_PRINCIPAL)
);

CREATE INDEX IX_TB_SOCIO_PERIODICO_VENC
    ON TB_SOCIO_PERIODICO_PAGAMENTO (NUMB_SOCIO_PRINCIPAL, DATA_VENCIMENTO);
